#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# This script simulates the git command for automated testing scenarios.
# -----------------------------------------------------------------------------

declare -r NAME=${0##*/}
declare -r BIN_DIR=$(cd $(dirname ${0}); pwd)
declare -- PATH=${PATH/${BIN_DIR}/}

export PATH

echo "$(date +%FT%T) -- ${NAME} ${@}" >> ${BIN_DIR}/${NAME}.log

function ltrim() {
  sed 's/^  //'
}

function worklog_base() {
  printf "%s\n" \
    $'0000000\t2022-01-06 22:34:56\tRoadrunner\tFirst draft git worklog' \
    $'9999999\t2022-01-05 01:02:03\tRoadrunner\tgit-rank: Remove column command' \
    $'8888888\t2022-01-04 02:22:34\tRoadrunner\tgit rank: New script to show commiter rank' \
    $'7777777\t2022-01-02 20:12:34\tWiley E. Coyote\tgit crank: Handle it better' \
    $'6666666\t2021-12-23 21:34:24\tRoadrunner\tgit sudo: Run as root.' \
    $'5555555\t2021-12-21 22:32:12\tWiley E. Coyote\tgit branch-branch: Like a tree.' \
    $'4444444\t2021-12-20 10:00:21\tRoadrunner\tgit fakeentry: Fake commit.' \
    $'3333333\t2021-12-19 12:01:21\tRoadrunner\tgit sample: test commit'
}

case "${@}" in
'rev-parse --show-toplevel')
  echo "/git/root"
  ;;
'branch')
  printf "  %s\n" "feature" "bugfix" "main"
  ;;
'rev-parse --abbrev-ref HEAD')
  echo 'bugfix'
  ;;
'checkout'*)
  echo "Switched to branch '${2}'"
  ;;
'fetch --prune')
  cat <<"  FETCH_PRUNE" | ltrim
  From github.com:uroesch/git-helpers
   - [deleted]         (none)     -> origin/feature
  FETCH_PRUNE
  ;;
'branch -d feature')
  echo "Deleted branch feature (was 092a7bb)."
  ;;
'rebase main')
  echo "Successfully rebased and updated refs/heads/..."
  ;;
'pull'*)
  cat <<"  PULL" | ltrim
  remote: Counting objects: 3, done.
  remote: Compressing objects: 100% (2/2), done.
  remote: Total 3 (delta 0), reused 0 (delta 0)
  Unpacking objects: 100% (3/3), done.
  From .../remote-repo
     45d5290..885f6c7  main     -> origin/main
  Updating 45d5290..885f6c7
  Fast-forward
   second_file.txt | 1 +
   1 file changed, 1 insertion(+)
   create mode 100644 second_file.txt
  PULL
  ;;
'push --tags')
  printf "%s\n" \
   "To github.com:uroesch/git-helpers" \
   " * [new tag]         foo -> foo"
  ;;
'push origin '*)
  cat <<"  PUSH" | ltrim
  Enumerating objects: 29, done.
  Counting objects: 100% (29/29), done.
  Delta compression using up to 8 threads
  Compressing objects: 100% (21/21), done.
  Writing objects: 100% (22/22), 3.28 KiB | 839.00 KiB/s, done.
  Total 22 (delta 13), reused 0 (delta 0), pack-reused 0
  Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
  remote:
  remote: Create a pull request for 'foobar' on GitHub by visiting:
  remote:      https://github.com/uroesch/git-helpers/pull/new/foobar
  remote:
  To github.com:uroesch/git-helpers
   * [new branch]      foobar -> foobar
  PUSH
  ;;
'branch -r --sort=committerdate --format=%(refname:lstrip=3)%09%(committername)%09%(committerdate:unix)')
  cat <<"  BRANCH" | ltrim
  veryold-branch	RoadRunner	1540790913
  experimental/ocrpdf	Wiley E. Coyote	1640790913
  packaging/debian	Crayon Shinchan	1640791190
  main	Chibi Marukochan	1643234609
  feature/scan2pdf	Globi	1643235907
  BRANCH
  ;;
'shortlog -n -s')
  cat <<"  SHORTLOG" | ltrim
  42 Road Runner
  39 Urs Roesch 
  33 Wiley E. Coyote
  21 Harry Potter
  11 github-actions[bot]
  SHORTLOG
  ;;
'config user.name')
  echo 'Roadrunner'
  ;;
'log --date=format:%F %T --pretty=format:%h%x09%ad%x09%an%x09%s --since=1514546715 --author=Roadrunner')
  worklog_base | grep Roadrunner | head -n 3
  ;;
'log --date=format:%F %T --pretty=format:%h%x09%ad%x09%an%x09%s --since=1483701915 --author=Roadrunner')
  worklog_base | grep Roadrunner
  ;;
'log --date=format:%F %T --pretty=format:%h%x09%ad%x09%an%x09%s --since=1514546715 --author=Wiley E. Coyote')
  worklog_base | grep 'Wiley E. Coyote'
  ;;
*)
  echo ${NAME} ${@}
  ;;
esac
