# -----------------------------------------------------------------------------
# Verify bash compatibility for git-helpers
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.1.0
# -----------------------------------------------------------------------------
name: bash-compatibility

on:
  push:
    branches:
    - workflow/*
  pull_request:
    branches:
    - master
    - main

jobs:
  bash-compatibility:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        bash:
        - '4.2'
        - '4.3'
        - '4.4'
        - '5.0'
        - '5.1'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Loop test
      shell: bash
      run: |
        function install-dependencies() {
          apk add \
            bats \
            coreutils \
            git \
            grep \
            make
        }
        docker run \
          --tty \
          --volume $(pwd):/git-helpers \
          --workdir /git-helpers \
          bash:${{ matrix.bash }} \
          bash -c "$(declare -f install-dependencies); install-dependencies && make test && echo \${BASH_VERSION}"
